pet_tables = {
	cats = {
				"Feline Familiar",
				"Cursed Birman",
				"Cinder Kitten",
				"Fluxfire Feline",
				"Mr. Bigglesworth",
				"Panther Cub",
				"Winterspring Cub",
				"Cat",
				"Sand Kitten",
				"Cheetah Cub",
				"Black Tabby Cat",
				"Bombay Cat",
				"Calico Cat",
				"Cornish Rex Cat",
				"Darkmoon Cub",
				"Orange Tabby Cat",
				"Sapphire Cub",
				"Siamese Cat",
				"Silver Tabby Cat",
				"Snow Cub",
				"White Kitten",
				"Risen Saber Kitten",
				"Lurking Owl Kitten",
				"Stout Alemental"
			},
	slimes = {
				"Disgusting Oozeling"
	},
	undead = {
				"Weebomination",
				"Cursed Birman",
				"Fossilized Hatchling",
				"Fragment of Suffering",
				"Stinkrot",
				"Unborn Val\'kyr",
				"Frostwolf Ghostpup",
				"Ghastly Kid",
				"Mr. Bigglesworth",
				"Ghostshell Crab",
				"Restless Shadeling",
				"Creepy Crate",
				"Lost of Lordaeron",
				"Bone Serpent",
				"Ghostly Skull"
	},
	viking = {
		"Baby Blizzard Bear",
		"Frostwolf Pup",
		"Unborn Val\'kyr",
		"Ashmaw Cub",
		"Hyjal Bear Cub",
		"Lifelike Mechanical Frostboar",
		"Stormborne Whelpling",
		"Emerald Proto-Whelp",
		"Fjord Worg Pup",
		"Dun Morogh Cub",
		"Snowfang",
		"Crow",
		"Summit Kid",
		"Artic Fox Kit",
		"Northern Hawk Owl"
	}
}